name: validate-test

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: innovationnorway/setup-terraform@v1
    - run: terraform fmt -check
    - run: |
        terraform init -backend=false -input=false
        terraform validate
      working-directory: ./test
  test:
    runs-on: ubuntu-latest
    if: github.event.pull_request.head.repo.fork == false
    steps:
    - uses: actions/checkout@v2
    - uses: innovationnorway/setup-terraform@v1
    - run: |
        terraform init -input=false
        terraform apply -auto-approve -input=false
        terraform destroy -auto-approve -input=false
      env:
        TFE_TOKEN: ${{ secrets.TFE_TOKEN_TEST }}
      working-directory: ./test
